name: Release CI

on:
  release:
    types:
      - created

jobs:

  deployProductionOnMasterRelease:
    name: Publish release to Netlify
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'created'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Storybook
        run: yarn build:storybook

      - name: Deploy production to Netlify
        uses: South-Paw/action-netlify-deploy@v1.0.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          build-dir: './storybook-static'

  publishPackage:
    name: Publish
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'created'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Configure NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Build package
        run: yarn build

      - name: Publish package
        uses: luvies/action-yarn-publish@v0.1.1
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
